; J2534 Pass-Thru — Feather M4 CAN Express (SAME51)
; PlatformIO build configuration

[env:feather_m4_can]
platform = atmelsam
board = adafruit_feather_m4_can
framework = arduino
lib_deps =
    adafruit/Adafruit CAN
    adafruit/Adafruit NeoPixel
    SdFat
    adafruit/RTClib
monitor_speed = 115200
lib_ignore = Adafruit TinyUSB Library
extra_scripts =
    pre:tools/build_kernel_registry.py
    post:uf2conv.py
build_flags =
    -DPASSTHRU_VERSION=\"1.5.0\"
