#!/usr/bin/env python3
"""
bin2header.py - Convert a raw binary to a C header with a byte array and
size/load-address macros. Used for embedding clean-room kernels into the
Flashy firmware build.

Usage:
    python bin2header.py <input.bin> <output.h> <symbol_prefix> [load_addr]

Example:
    python bin2header.py Cernels/e92_read/kernel.bin \\
        src/cernel_e92_private.h CERNEL_E92 0x40001000

Produces an <output.h> with:
    #define CERNEL_E92_SIZE        808
    #define CERNEL_E92_LOAD_ADDR   0x40001000UL
    static const uint8_t CERNEL_E92_KERNEL[] PROGMEM = { 0x..., ... };
"""

import os
import sys
import textwrap


def main():
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(1)

    in_path = sys.argv[1]
    out_path = sys.argv[2]
    prefix = sys.argv[3]
    load_addr = int(sys.argv[4], 0) if len(sys.argv) > 4 else 0x40001000

    with open(in_path, 'rb') as f:
        data = f.read()

    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_bytes = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append(f'    {hex_bytes},')

    header = textwrap.dedent(f'''\
        /*
         * {os.path.basename(out_path)} - Generated by bin2header.py.
         * Source: {in_path} ({len(data)} bytes)
         * Do not edit by hand.
         */

        #ifndef {prefix}_H
        #define {prefix}_H

        #include <stdint.h>
        #ifndef PROGMEM
        #define PROGMEM
        #endif

        #define {prefix}_KERNEL_SIZE        {len(data)}
        #define {prefix}_KERNEL_LOAD_ADDR   0x{load_addr:08X}UL
        #define {prefix}_SIZE               {prefix}_KERNEL_SIZE       /* alias */
        #define {prefix}_LOAD_ADDR          {prefix}_KERNEL_LOAD_ADDR  /* alias */

        static const uint8_t {prefix}_KERNEL[] PROGMEM = {{
        ''')

    footer = textwrap.dedent(f'''\
        }};

        #endif /* {prefix}_H */
        ''')

    with open(out_path, 'w', encoding='ascii') as f:
        f.write(header)
        f.write('\n'.join(lines))
        f.write('\n')
        f.write(footer)

    print(f'Wrote {out_path}: {len(data)} bytes, prefix {prefix}, load 0x{load_addr:08X}')


if __name__ == '__main__':
    main()
